### ISSUE TITLE
Angle optimization

### ISSUE THREAD

**Issue by xranby** [tgreiser/etherdream#10]
The Journal of the Society for Art and Science Vol. 7 No. 4 pp. 155 - 169
contains an easy way to improve sharpness of picture quality by
compensate for the inertia effects when the laser is taking a sharp turns.
the paper reveal that there is an almost linear relationship between the angle of the turn and the delay to be used to mitigate the effect. - page 161
http://art-science.org/journal/v7n4/v7n4pp155/artsci-v7n4pp155.pdf

masterpj55 has invented a different way to render correct angles and bent lines by taking advantage of the inertia effect rather than eliminating them: https://twitter.com/masterpj55/status/853291275545653248/photo/1
this approach do not need any added delays hence it is a superior technique.
however masterpj55's approach would require a pass that move the x and y of the buffer data as a better way to compensate or create the desired straight/bent line effect.
masterpj55's method have not been described in any laser research however pragmatically masterpj55 have demonstrated that the method work.

**Comment by tgreiser** [comment]
This is a low priority project for me right now, but my plans are more in line with the first option. There is some related research on load balancing type optimization here.

http://art-science.org/journal/v8n1/v8n1pp1/artsci-v8n1pp1.pdf

marsterpj55's example looks quite optimized, but it does not sound appropriate for real-time use. As he says it is not an algorithm. Hand drawn? https://twitter.com/xranby/status/855322834612113408

> not many do (use this method) because it takes a lot of time and the wrong moves can damage galvo sets

**Comment by xranby** [comment]
Indeed marsterpj55 image is hand drawn however it is useful as a reference what may be possible. I will experiment if I can do similar moves algorithmically and report back.
